name: Build QuickFIX Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache vcpkg installed directory
        uses: actions/cache@v4
        with:
          path: vcpkg_installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-
            
      # Install ODBC Driver for SQL Server via MSI
      - name: Install ODBC Driver for SQL Server
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2335671" -OutFile msodbcsql18.msi
          msiexec /i msodbcsql18.msi /quiet /qn /norestart IACCEPTMSODBCSQLLICENSETERMS=YES

      # Install library dependencies via vcpkg
      - name: Install Dependencies via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install libmysql:x64-windows libxml2:x64-windows libpq:x64-windows
          cd ..  

      - name: Add vcpkg binaries to PATH
        run: |
          echo "${{ github.workspace }}\vcpkg\installed\x64-windows\bin" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      # Unzip the QuickFIX source archive
      - name: Unpack QuickFIX sources
        run: tar -xf quickfix-1.15.1.zip

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Python build dependencies
        run: pip install setuptools wheel

      # Configure and build with CMake and Ninja using vcpkg toolchain
      - name: Build with CMake/Ninja
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake -G Ninja `
            -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake" `
            -DCMAKE_CXX_FLAGS="/EHsc /MD" `
            -DCMAKE_EXE_LINKER_FLAGS="quickfix.lib ws2_32.lib" `
            -Dquickfix_INCLUDE_DIR="../quickfix-1.15.1" `
            -Dquickfix_LIB_DIR="../quickfix-1.15.1/lib" `
            -DHAVE_SSL=ON `
            -DLIBXML2_INCLUDE_DIR="../vcpkg/installed/x64-windows/include" `
            -DLIBXML2_LIBRARIES="../vcpkg/installed/x64-windows/lib/libxml2.lib" `
            -DMYSQL_INCLUDE_DIR="../vcpkg/installed/x64-windows/include" `
            -DMYSQL_LIBRARY="../vcpkg/installed/x64-windows/lib/libmysql.lib" `
            -DPOSTGRESQL_INCLUDE_DIR="../vcpkg/installed/x64-windows/include" `
            -DPOSTGRESQL_LIBRARY="../vcpkg/installed/x64-windows/lib/libpq.lib" `
            -DHAVE_ODBC=ON `
            -DHAVE_MYSQL=ON `
            -DHAVE_POSTGRESQL=ON `
            ../quickfix-1.15.1
          ninja

      - name: Build Wheel
        run: python setup.py bdist_wheel

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-wheel
          path: dist/*. whl
